import React from 'react';

const RecentReports = () => {
  const recentReportsData = [
    {
      id: 1,
      reportName: 'User Activity Report',
      generatedBy: 'admin1',
      dateRange: '15 May 2020 - 15 May 2020',
      generatedOn: '15 May 2020, 10:00 pm',
    },
    {
      id: 2,
      reportName: 'Financial Summary Report',
      generatedBy: 'admin2',
      dateRange: '01 Jan 2024 - 31 Jan 2024',
      generatedOn: '01 Feb 2024, 09:00 am',
    },
  ];


  const handleDownload = (report) => {

    const headers = "Report Name,Generated By,Date Range,Generated On\n";
    const row = `${report.reportName},${report.generatedBy},${report.dateRange},${report.generatedOn}`;
    const csvContent = headers + row;


    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `${report.reportName.replace(/\s+/g, '_')}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="mt-8 m-8 bg-[#0a111a] border border-gray-800 rounded-xl p-6">
      <h3 className="text-lg font-semibold text-white mb-6">Recent Reports</h3>

      <div className="overflow-x-auto">
        <table className="w-full text-left">
          <thead>
            <tr className="bg-[#1e2733] text-gray-400 text-sm">
              <th className="px-6 py-4 rounded-l-xl font-medium">Report Name</th>
              <th className="px-6 py-4 font-medium">Generated By</th>
              <th className="px-6 py-4 font-medium text-center">Date Range</th>
              <th className="px-6 py-4 font-medium text-center">Generated On</th>
              <th className="px-6 py-4 rounded-r-xl font-medium text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-800">
            {recentReportsData.map((report) => (
              <tr key={report.id} className="hover:bg-[#121d2b] transition-colors group">
                <td className="px-6 py-5 text-sm text-white font-medium">
                  {report.reportName}
                </td>
                <td className="px-6 py-5 text-sm text-gray-400">
                  {report.generatedBy}
                </td>
                <td className="px-6 py-5 text-sm text-gray-300 text-center">
                  {report.dateRange}
                </td>
                <td className="px-6 py-5 text-sm text-gray-300 text-center">
                  {report.generatedOn}
                </td>
                <td className="px-6 py-5 text-right">
                  <button 
                    onClick={() => handleDownload(report)}
                    className="text-[#facc15] hover:text-yellow-500 text-sm font-bold transition-colors active:scale-90"
                  >
                    Download
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default RecentReports;